// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `AzureSQL`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `empty`
//     Include Views:          `True`


// -----------------------------------------------------------------------------------------
// Failed to read database schema - Format of the initialization string does not conform to specification starting at index 0.
// -----------------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lunch.Core.Models.Database
{
}
