// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `AzureSQL`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:jh2haawn58.database.windows.net,1433;Database=WhatsForLunch;User ID=whatsforlunch@jh2haawn58;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lunch.Core.Models.Template
{
    /// <summary>
    /// A class which represents the RestaurantRatings table.
    /// </summary>
	[Table("RestaurantRatings")]
	public partial class RestaurantRating
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int UserID { get; set; }
		public virtual int RestaurantID { get; set; }
		public virtual int Rating { get; set; }
	}

    /// <summary>
    /// A class which represents the Votes table.
    /// </summary>
	[Table("Votes")]
	public partial class Vote
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int UserID { get; set; }
		public virtual int RestaurantID { get; set; }
		public virtual DateTime VoteDate { get; set; }
	}

    /// <summary>
    /// A class which represents the JobLog table.
    /// </summary>
	[Table("JobLog")]
	public partial class JobLog
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Category { get; set; }
		public virtual string Message { get; set; }
		public virtual DateTime LogDTM { get; set; }
		public virtual int? JobID { get; set; }
	}

    /// <summary>
    /// A class which represents the Job table.
    /// </summary>
	[Table("Job")]
	public partial class Job
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string MethodName { get; set; }
		public virtual string ParametersJson { get; set; }
		public virtual DateTime RunDate { get; set; }
		public virtual DateTime CreatedDate { get; set; }
		public virtual bool HasRun { get; set; }
	}

    /// <summary>
    /// A class which represents the Restaurant table.
    /// </summary>
	[Table("Restaurant")]
	public partial class Restaurant
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string RestaurantName { get; set; }
		public virtual int? PreferredDayOfWeek { get; set; }
		public virtual int? RestaurantTypeID { get; set; }
	}

    /// <summary>
    /// A class which represents the RestaurantType table.
    /// </summary>
	[Table("RestaurantType")]
	public partial class RestaurantType
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string TypeName { get; set; }
	}

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
	public partial class User
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string FullName { get; set; }
		public virtual string Email { get; set; }
		public virtual Guid? GUID { get; set; }
		public virtual bool SendMail1 { get; set; }
		public virtual bool SendMail2 { get; set; }
		public virtual bool SendMail3 { get; set; }
		public virtual bool SendMail4 { get; set; }
	}

    /// <summary>
    /// A class which represents the Holidays table.
    /// </summary>
	[Table("Holidays")]
	public partial class Holiday
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual DateTime ExcludedDate { get; set; }
	}

}
